FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && apt-get install -y \
    iverilog \
    gtkwave \
    yosys \
    make \
    git \
    python3 \
    python3-pip \
    && apt-get clean
